//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("CandiesSellerModel", "FK__order__id_user__1A14E395", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CandiesSellerWCF.Data.user), "order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CandiesSellerWCF.Data.order), true)]

#endregion

namespace CandiesSellerWCF.Data
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class CandiesSellerEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet CandiesSellerEntities à l'aide de la chaîne de connexion trouvée dans la section 'CandiesSellerEntities' du fichier de configuration d'application.
        /// </summary>
        public CandiesSellerEntities() : base("name=CandiesSellerEntities", "CandiesSellerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet CandiesSellerEntities.
        /// </summary>
        public CandiesSellerEntities(string connectionString) : base(connectionString, "CandiesSellerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet CandiesSellerEntities.
        /// </summary>
        public CandiesSellerEntities(EntityConnection connection) : base(connection, "CandiesSellerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<item> item
        {
            get
            {
                if ((_item == null))
                {
                    _item = base.CreateObjectSet<item>("item");
                }
                return _item;
            }
        }
        private ObjectSet<item> _item;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<order> order
        {
            get
            {
                if ((_order == null))
                {
                    _order = base.CreateObjectSet<order>("order");
                }
                return _order;
            }
        }
        private ObjectSet<order> _order;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<stock> stock
        {
            get
            {
                if ((_stock == null))
                {
                    _stock = base.CreateObjectSet<stock>("stock");
                }
                return _stock;
            }
        }
        private ObjectSet<stock> _stock;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet item. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToitem(item item)
        {
            base.AddObject("item", item);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet order. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToorder(order order)
        {
            base.AddObject("order", order);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet stock. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTostock(stock stock)
        {
            base.AddObject("stock", stock);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet user. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CandiesSellerModel", Name="item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class item : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet item.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static item Createitem(global::System.Int32 id)
        {
            item item = new item();
            item.Id = id;
            return item;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, true, "nom");
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private Nullable<global::System.Int32> _nombre;
        partial void OnnombreChanging(Nullable<global::System.Int32> value);
        partial void OnnombreChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CandiesSellerModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet order.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static order Createorder(global::System.Int32 id)
        {
            order order = new order();
            order.Id = id;
            return order;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Skittles
        {
            get
            {
                return _Skittles;
            }
            set
            {
                OnSkittlesChanging(value);
                ReportPropertyChanging("Skittles");
                _Skittles = StructuralObject.SetValidValue(value, "Skittles");
                ReportPropertyChanged("Skittles");
                OnSkittlesChanged();
            }
        }
        private Nullable<global::System.Int32> _Skittles;
        partial void OnSkittlesChanging(Nullable<global::System.Int32> value);
        partial void OnSkittlesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cottoncandy
        {
            get
            {
                return _cottoncandy;
            }
            set
            {
                OncottoncandyChanging(value);
                ReportPropertyChanging("cottoncandy");
                _cottoncandy = StructuralObject.SetValidValue(value, "cottoncandy");
                ReportPropertyChanged("cottoncandy");
                OncottoncandyChanged();
            }
        }
        private Nullable<global::System.Int32> _cottoncandy;
        partial void OncottoncandyChanging(Nullable<global::System.Int32> value);
        partial void OncottoncandyChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> creamegg
        {
            get
            {
                return _creamegg;
            }
            set
            {
                OncreameggChanging(value);
                ReportPropertyChanging("creamegg");
                _creamegg = StructuralObject.SetValidValue(value, "creamegg");
                ReportPropertyChanged("creamegg");
                OncreameggChanged();
            }
        }
        private Nullable<global::System.Int32> _creamegg;
        partial void OncreameggChanging(Nullable<global::System.Int32> value);
        partial void OncreameggChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> jawbreaker
        {
            get
            {
                return _jawbreaker;
            }
            set
            {
                OnjawbreakerChanging(value);
                ReportPropertyChanging("jawbreaker");
                _jawbreaker = StructuralObject.SetValidValue(value, "jawbreaker");
                ReportPropertyChanged("jawbreaker");
                OnjawbreakerChanged();
            }
        }
        private Nullable<global::System.Int32> _jawbreaker;
        partial void OnjawbreakerChanging(Nullable<global::System.Int32> value);
        partial void OnjawbreakerChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> redvinelicornes
        {
            get
            {
                return _redvinelicornes;
            }
            set
            {
                OnredvinelicornesChanging(value);
                ReportPropertyChanging("redvinelicornes");
                _redvinelicornes = StructuralObject.SetValidValue(value, "redvinelicornes");
                ReportPropertyChanged("redvinelicornes");
                OnredvinelicornesChanged();
            }
        }
        private Nullable<global::System.Int32> _redvinelicornes;
        partial void OnredvinelicornesChanging(Nullable<global::System.Int32> value);
        partial void OnredvinelicornesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sugardaddy
        {
            get
            {
                return _sugardaddy;
            }
            set
            {
                OnsugardaddyChanging(value);
                ReportPropertyChanging("sugardaddy");
                _sugardaddy = StructuralObject.SetValidValue(value, "sugardaddy");
                ReportPropertyChanged("sugardaddy");
                OnsugardaddyChanged();
            }
        }
        private Nullable<global::System.Int32> _sugardaddy;
        partial void OnsugardaddyChanging(Nullable<global::System.Int32> value);
        partial void OnsugardaddyChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value, "id_user");
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private Nullable<global::System.Int32> _id_user;
        partial void Onid_userChanging(Nullable<global::System.Int32> value);
        partial void Onid_userChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CandiesSellerModel", "FK__order__id_user__1A14E395", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("CandiesSellerModel.FK__order__id_user__1A14E395", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("CandiesSellerModel.FK__order__id_user__1A14E395", "user").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("CandiesSellerModel.FK__order__id_user__1A14E395", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("CandiesSellerModel.FK__order__id_user__1A14E395", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CandiesSellerModel", Name="stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stock : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet stock.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        /// <param name="skittles">Valeur initiale de la propriété Skittles.</param>
        /// <param name="cottoncandy">Valeur initiale de la propriété cottoncandy.</param>
        /// <param name="creamegg">Valeur initiale de la propriété creamegg.</param>
        /// <param name="jawbreaker">Valeur initiale de la propriété jawbreaker.</param>
        /// <param name="redvinelicornes">Valeur initiale de la propriété redvinelicornes.</param>
        /// <param name="sugardaddy">Valeur initiale de la propriété sugardaddy.</param>
        /// <param name="skittles_cost">Valeur initiale de la propriété Skittles_cost.</param>
        /// <param name="cottoncandy_cost">Valeur initiale de la propriété cottoncandy_cost.</param>
        /// <param name="creamegg_cost">Valeur initiale de la propriété creamegg_cost.</param>
        /// <param name="jawbreaker_cost">Valeur initiale de la propriété jawbreaker_cost.</param>
        /// <param name="redvinelicornes_cost">Valeur initiale de la propriété redvinelicornes_cost.</param>
        /// <param name="sugardaddy_cost">Valeur initiale de la propriété sugardaddy_cost.</param>
        public static stock Createstock(global::System.Int32 id, global::System.Int32 skittles, global::System.Int32 cottoncandy, global::System.Int32 creamegg, global::System.Int32 jawbreaker, global::System.Int32 redvinelicornes, global::System.Int32 sugardaddy, global::System.Int32 skittles_cost, global::System.Int32 cottoncandy_cost, global::System.Int32 creamegg_cost, global::System.Int32 jawbreaker_cost, global::System.Int32 redvinelicornes_cost, global::System.Int32 sugardaddy_cost)
        {
            stock stock = new stock();
            stock.Id = id;
            stock.Skittles = skittles;
            stock.cottoncandy = cottoncandy;
            stock.creamegg = creamegg;
            stock.jawbreaker = jawbreaker;
            stock.redvinelicornes = redvinelicornes;
            stock.sugardaddy = sugardaddy;
            stock.Skittles_cost = skittles_cost;
            stock.cottoncandy_cost = cottoncandy_cost;
            stock.creamegg_cost = creamegg_cost;
            stock.jawbreaker_cost = jawbreaker_cost;
            stock.redvinelicornes_cost = redvinelicornes_cost;
            stock.sugardaddy_cost = sugardaddy_cost;
            return stock;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Skittles
        {
            get
            {
                return _Skittles;
            }
            set
            {
                OnSkittlesChanging(value);
                ReportPropertyChanging("Skittles");
                _Skittles = StructuralObject.SetValidValue(value, "Skittles");
                ReportPropertyChanged("Skittles");
                OnSkittlesChanged();
            }
        }
        private global::System.Int32 _Skittles;
        partial void OnSkittlesChanging(global::System.Int32 value);
        partial void OnSkittlesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cottoncandy
        {
            get
            {
                return _cottoncandy;
            }
            set
            {
                OncottoncandyChanging(value);
                ReportPropertyChanging("cottoncandy");
                _cottoncandy = StructuralObject.SetValidValue(value, "cottoncandy");
                ReportPropertyChanged("cottoncandy");
                OncottoncandyChanged();
            }
        }
        private global::System.Int32 _cottoncandy;
        partial void OncottoncandyChanging(global::System.Int32 value);
        partial void OncottoncandyChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 creamegg
        {
            get
            {
                return _creamegg;
            }
            set
            {
                OncreameggChanging(value);
                ReportPropertyChanging("creamegg");
                _creamegg = StructuralObject.SetValidValue(value, "creamegg");
                ReportPropertyChanged("creamegg");
                OncreameggChanged();
            }
        }
        private global::System.Int32 _creamegg;
        partial void OncreameggChanging(global::System.Int32 value);
        partial void OncreameggChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 jawbreaker
        {
            get
            {
                return _jawbreaker;
            }
            set
            {
                OnjawbreakerChanging(value);
                ReportPropertyChanging("jawbreaker");
                _jawbreaker = StructuralObject.SetValidValue(value, "jawbreaker");
                ReportPropertyChanged("jawbreaker");
                OnjawbreakerChanged();
            }
        }
        private global::System.Int32 _jawbreaker;
        partial void OnjawbreakerChanging(global::System.Int32 value);
        partial void OnjawbreakerChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redvinelicornes
        {
            get
            {
                return _redvinelicornes;
            }
            set
            {
                OnredvinelicornesChanging(value);
                ReportPropertyChanging("redvinelicornes");
                _redvinelicornes = StructuralObject.SetValidValue(value, "redvinelicornes");
                ReportPropertyChanged("redvinelicornes");
                OnredvinelicornesChanged();
            }
        }
        private global::System.Int32 _redvinelicornes;
        partial void OnredvinelicornesChanging(global::System.Int32 value);
        partial void OnredvinelicornesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sugardaddy
        {
            get
            {
                return _sugardaddy;
            }
            set
            {
                OnsugardaddyChanging(value);
                ReportPropertyChanging("sugardaddy");
                _sugardaddy = StructuralObject.SetValidValue(value, "sugardaddy");
                ReportPropertyChanged("sugardaddy");
                OnsugardaddyChanged();
            }
        }
        private global::System.Int32 _sugardaddy;
        partial void OnsugardaddyChanging(global::System.Int32 value);
        partial void OnsugardaddyChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Skittles_cost
        {
            get
            {
                return _Skittles_cost;
            }
            set
            {
                OnSkittles_costChanging(value);
                ReportPropertyChanging("Skittles_cost");
                _Skittles_cost = StructuralObject.SetValidValue(value, "Skittles_cost");
                ReportPropertyChanged("Skittles_cost");
                OnSkittles_costChanged();
            }
        }
        private global::System.Int32 _Skittles_cost;
        partial void OnSkittles_costChanging(global::System.Int32 value);
        partial void OnSkittles_costChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cottoncandy_cost
        {
            get
            {
                return _cottoncandy_cost;
            }
            set
            {
                Oncottoncandy_costChanging(value);
                ReportPropertyChanging("cottoncandy_cost");
                _cottoncandy_cost = StructuralObject.SetValidValue(value, "cottoncandy_cost");
                ReportPropertyChanged("cottoncandy_cost");
                Oncottoncandy_costChanged();
            }
        }
        private global::System.Int32 _cottoncandy_cost;
        partial void Oncottoncandy_costChanging(global::System.Int32 value);
        partial void Oncottoncandy_costChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 creamegg_cost
        {
            get
            {
                return _creamegg_cost;
            }
            set
            {
                Oncreamegg_costChanging(value);
                ReportPropertyChanging("creamegg_cost");
                _creamegg_cost = StructuralObject.SetValidValue(value, "creamegg_cost");
                ReportPropertyChanged("creamegg_cost");
                Oncreamegg_costChanged();
            }
        }
        private global::System.Int32 _creamegg_cost;
        partial void Oncreamegg_costChanging(global::System.Int32 value);
        partial void Oncreamegg_costChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 jawbreaker_cost
        {
            get
            {
                return _jawbreaker_cost;
            }
            set
            {
                Onjawbreaker_costChanging(value);
                ReportPropertyChanging("jawbreaker_cost");
                _jawbreaker_cost = StructuralObject.SetValidValue(value, "jawbreaker_cost");
                ReportPropertyChanged("jawbreaker_cost");
                Onjawbreaker_costChanged();
            }
        }
        private global::System.Int32 _jawbreaker_cost;
        partial void Onjawbreaker_costChanging(global::System.Int32 value);
        partial void Onjawbreaker_costChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 redvinelicornes_cost
        {
            get
            {
                return _redvinelicornes_cost;
            }
            set
            {
                Onredvinelicornes_costChanging(value);
                ReportPropertyChanging("redvinelicornes_cost");
                _redvinelicornes_cost = StructuralObject.SetValidValue(value, "redvinelicornes_cost");
                ReportPropertyChanged("redvinelicornes_cost");
                Onredvinelicornes_costChanged();
            }
        }
        private global::System.Int32 _redvinelicornes_cost;
        partial void Onredvinelicornes_costChanging(global::System.Int32 value);
        partial void Onredvinelicornes_costChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sugardaddy_cost
        {
            get
            {
                return _sugardaddy_cost;
            }
            set
            {
                Onsugardaddy_costChanging(value);
                ReportPropertyChanging("sugardaddy_cost");
                _sugardaddy_cost = StructuralObject.SetValidValue(value, "sugardaddy_cost");
                ReportPropertyChanged("sugardaddy_cost");
                Onsugardaddy_costChanged();
            }
        }
        private global::System.Int32 _sugardaddy_cost;
        partial void Onsugardaddy_costChanging(global::System.Int32 value);
        partial void Onsugardaddy_costChanged();

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CandiesSellerModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet user.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété Id.</param>
        public static user Createuser(global::System.Int32 id)
        {
            user user = new user();
            user.Id = id;
            return user;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pseudo
        {
            get
            {
                return _pseudo;
            }
            set
            {
                OnpseudoChanging(value);
                ReportPropertyChanging("pseudo");
                _pseudo = StructuralObject.SetValidValue(value, true, "pseudo");
                ReportPropertyChanged("pseudo");
                OnpseudoChanged();
            }
        }
        private global::System.String _pseudo;
        partial void OnpseudoChanging(global::System.String value);
        partial void OnpseudoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CandiesSellerModel", "FK__order__id_user__1A14E395", "order")]
        public EntityCollection<order> order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order>("CandiesSellerModel.FK__order__id_user__1A14E395", "order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order>("CandiesSellerModel.FK__order__id_user__1A14E395", "order", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
