//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandiesSellerWCF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.order = new HashSet<order>();
        }
    
        public int Id { get; set; }
        public string pseudo { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
