//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandiesSellerWPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stockBusiness", Namespace="http://schemas.datacontract.org/2004/07/CandiesSellerWCF.Business")]
    [System.SerializableAttribute()]
    public partial class stockBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SkittlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Skittles_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cottoncandyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cottoncandy_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double creameggField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double creamegg_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double jawbreakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double jawbreaker_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double redvinelicornesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double redvinelicornes_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sugardaddyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sugardaddy_costField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Skittles {
            get {
                return this.SkittlesField;
            }
            set {
                if ((this.SkittlesField.Equals(value) != true)) {
                    this.SkittlesField = value;
                    this.RaisePropertyChanged("Skittles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Skittles_cost {
            get {
                return this.Skittles_costField;
            }
            set {
                if ((this.Skittles_costField.Equals(value) != true)) {
                    this.Skittles_costField = value;
                    this.RaisePropertyChanged("Skittles_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cottoncandy {
            get {
                return this.cottoncandyField;
            }
            set {
                if ((this.cottoncandyField.Equals(value) != true)) {
                    this.cottoncandyField = value;
                    this.RaisePropertyChanged("cottoncandy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double cottoncandy_cost {
            get {
                return this.cottoncandy_costField;
            }
            set {
                if ((this.cottoncandy_costField.Equals(value) != true)) {
                    this.cottoncandy_costField = value;
                    this.RaisePropertyChanged("cottoncandy_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double creamegg {
            get {
                return this.creameggField;
            }
            set {
                if ((this.creameggField.Equals(value) != true)) {
                    this.creameggField = value;
                    this.RaisePropertyChanged("creamegg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double creamegg_cost {
            get {
                return this.creamegg_costField;
            }
            set {
                if ((this.creamegg_costField.Equals(value) != true)) {
                    this.creamegg_costField = value;
                    this.RaisePropertyChanged("creamegg_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double jawbreaker {
            get {
                return this.jawbreakerField;
            }
            set {
                if ((this.jawbreakerField.Equals(value) != true)) {
                    this.jawbreakerField = value;
                    this.RaisePropertyChanged("jawbreaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double jawbreaker_cost {
            get {
                return this.jawbreaker_costField;
            }
            set {
                if ((this.jawbreaker_costField.Equals(value) != true)) {
                    this.jawbreaker_costField = value;
                    this.RaisePropertyChanged("jawbreaker_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double redvinelicornes {
            get {
                return this.redvinelicornesField;
            }
            set {
                if ((this.redvinelicornesField.Equals(value) != true)) {
                    this.redvinelicornesField = value;
                    this.RaisePropertyChanged("redvinelicornes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double redvinelicornes_cost {
            get {
                return this.redvinelicornes_costField;
            }
            set {
                if ((this.redvinelicornes_costField.Equals(value) != true)) {
                    this.redvinelicornes_costField = value;
                    this.RaisePropertyChanged("redvinelicornes_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sugardaddy {
            get {
                return this.sugardaddyField;
            }
            set {
                if ((this.sugardaddyField.Equals(value) != true)) {
                    this.sugardaddyField = value;
                    this.RaisePropertyChanged("sugardaddy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sugardaddy_cost {
            get {
                return this.sugardaddy_costField;
            }
            set {
                if ((this.sugardaddy_costField.Equals(value) != true)) {
                    this.sugardaddy_costField = value;
                    this.RaisePropertyChanged("sugardaddy_cost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="priceBusiness", Namespace="http://schemas.datacontract.org/2004/07/CandiesSellerWCF.Business")]
    [System.SerializableAttribute()]
    public partial class priceBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Skittle_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cottoncandy_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int creamegg_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jawbreaker_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int redvinelicornes_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sugardaddy_priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Skittle_price {
            get {
                return this.Skittle_priceField;
            }
            set {
                if ((this.Skittle_priceField.Equals(value) != true)) {
                    this.Skittle_priceField = value;
                    this.RaisePropertyChanged("Skittle_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cottoncandy_price {
            get {
                return this.cottoncandy_priceField;
            }
            set {
                if ((this.cottoncandy_priceField.Equals(value) != true)) {
                    this.cottoncandy_priceField = value;
                    this.RaisePropertyChanged("cottoncandy_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creamegg_price {
            get {
                return this.creamegg_priceField;
            }
            set {
                if ((this.creamegg_priceField.Equals(value) != true)) {
                    this.creamegg_priceField = value;
                    this.RaisePropertyChanged("creamegg_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jawbreaker_price {
            get {
                return this.jawbreaker_priceField;
            }
            set {
                if ((this.jawbreaker_priceField.Equals(value) != true)) {
                    this.jawbreaker_priceField = value;
                    this.RaisePropertyChanged("jawbreaker_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int redvinelicornes_price {
            get {
                return this.redvinelicornes_priceField;
            }
            set {
                if ((this.redvinelicornes_priceField.Equals(value) != true)) {
                    this.redvinelicornes_priceField = value;
                    this.RaisePropertyChanged("redvinelicornes_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sugardaddy_price {
            get {
                return this.sugardaddy_priceField;
            }
            set {
                if ((this.sugardaddy_priceField.Equals(value) != true)) {
                    this.sugardaddy_priceField = value;
                    this.RaisePropertyChanged("sugardaddy_price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userBusiness", Namespace="http://schemas.datacontract.org/2004/07/CandiesSellerWCF.Business")]
    [System.SerializableAttribute()]
    public partial class userBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Panier", Namespace="http://schemas.datacontract.org/2004/07/CandiesSellerWCF.Business")]
    [System.SerializableAttribute()]
    public partial class Panier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PricePanierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QCottonCandyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QCreamEggField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QJawbreakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QRedvinesLicornesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QSkittlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QSugarDaddyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PricePanier {
            get {
                return this.PricePanierField;
            }
            set {
                if ((this.PricePanierField.Equals(value) != true)) {
                    this.PricePanierField = value;
                    this.RaisePropertyChanged("PricePanier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QCottonCandy {
            get {
                return this.QCottonCandyField;
            }
            set {
                if ((this.QCottonCandyField.Equals(value) != true)) {
                    this.QCottonCandyField = value;
                    this.RaisePropertyChanged("QCottonCandy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QCreamEgg {
            get {
                return this.QCreamEggField;
            }
            set {
                if ((this.QCreamEggField.Equals(value) != true)) {
                    this.QCreamEggField = value;
                    this.RaisePropertyChanged("QCreamEgg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QJawbreaker {
            get {
                return this.QJawbreakerField;
            }
            set {
                if ((this.QJawbreakerField.Equals(value) != true)) {
                    this.QJawbreakerField = value;
                    this.RaisePropertyChanged("QJawbreaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QRedvinesLicornes {
            get {
                return this.QRedvinesLicornesField;
            }
            set {
                if ((this.QRedvinesLicornesField.Equals(value) != true)) {
                    this.QRedvinesLicornesField = value;
                    this.RaisePropertyChanged("QRedvinesLicornes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QSkittles {
            get {
                return this.QSkittlesField;
            }
            set {
                if ((this.QSkittlesField.Equals(value) != true)) {
                    this.QSkittlesField = value;
                    this.RaisePropertyChanged("QSkittles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QSugarDaddy {
            get {
                return this.QSugarDaddyField;
            }
            set {
                if ((this.QSugarDaddyField.Equals(value) != true)) {
                    this.QSugarDaddyField = value;
                    this.RaisePropertyChanged("QSugarDaddy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICandies")]
    public interface ICandies {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/getStock", ReplyAction="http://tempuri.org/ICandies/getStockResponse")]
        CandiesSellerWPF.ServiceReference1.stockBusiness getStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/getStock", ReplyAction="http://tempuri.org/ICandies/getStockResponse")]
        System.Threading.Tasks.Task<CandiesSellerWPF.ServiceReference1.stockBusiness> getStockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setStock", ReplyAction="http://tempuri.org/ICandies/setStockResponse")]
        bool setStock(int Skittles_d, int cottoncandy_d, int creamegg_d, int jawbreaker_d, int redvinelicornes_d, int sugardaddy_d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setStock", ReplyAction="http://tempuri.org/ICandies/setStockResponse")]
        System.Threading.Tasks.Task<bool> setStockAsync(int Skittles_d, int cottoncandy_d, int creamegg_d, int jawbreaker_d, int redvinelicornes_d, int sugardaddy_d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/getPrice", ReplyAction="http://tempuri.org/ICandies/getPriceResponse")]
        CandiesSellerWPF.ServiceReference1.priceBusiness getPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/getPrice", ReplyAction="http://tempuri.org/ICandies/getPriceResponse")]
        System.Threading.Tasks.Task<CandiesSellerWPF.ServiceReference1.priceBusiness> getPriceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setPrice", ReplyAction="http://tempuri.org/ICandies/setPriceResponse")]
        bool setPrice(int Skittles_cost_d, int cottoncandy_cost_d, int creamegg_cost_d, int jawbreaker_cost_d, int redvinelicornes_cost_d, int sugardaddy_cost_d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setPrice", ReplyAction="http://tempuri.org/ICandies/setPriceResponse")]
        System.Threading.Tasks.Task<bool> setPriceAsync(int Skittles_cost_d, int cottoncandy_cost_d, int creamegg_cost_d, int jawbreaker_cost_d, int redvinelicornes_cost_d, int sugardaddy_cost_d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setOrder", ReplyAction="http://tempuri.org/ICandies/setOrderResponse")]
        bool setOrder(CandiesSellerWPF.ServiceReference1.userBusiness unUser, CandiesSellerWPF.ServiceReference1.Panier uneOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICandies/setOrder", ReplyAction="http://tempuri.org/ICandies/setOrderResponse")]
        System.Threading.Tasks.Task<bool> setOrderAsync(CandiesSellerWPF.ServiceReference1.userBusiness unUser, CandiesSellerWPF.ServiceReference1.Panier uneOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICandiesChannel : CandiesSellerWPF.ServiceReference1.ICandies, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CandiesClient : System.ServiceModel.ClientBase<CandiesSellerWPF.ServiceReference1.ICandies>, CandiesSellerWPF.ServiceReference1.ICandies {
        
        public CandiesClient() {
        }
        
        public CandiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CandiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CandiesSellerWPF.ServiceReference1.stockBusiness getStock() {
            return base.Channel.getStock();
        }
        
        public System.Threading.Tasks.Task<CandiesSellerWPF.ServiceReference1.stockBusiness> getStockAsync() {
            return base.Channel.getStockAsync();
        }
        
        public bool setStock(int Skittles_d, int cottoncandy_d, int creamegg_d, int jawbreaker_d, int redvinelicornes_d, int sugardaddy_d) {
            return base.Channel.setStock(Skittles_d, cottoncandy_d, creamegg_d, jawbreaker_d, redvinelicornes_d, sugardaddy_d);
        }
        
        public System.Threading.Tasks.Task<bool> setStockAsync(int Skittles_d, int cottoncandy_d, int creamegg_d, int jawbreaker_d, int redvinelicornes_d, int sugardaddy_d) {
            return base.Channel.setStockAsync(Skittles_d, cottoncandy_d, creamegg_d, jawbreaker_d, redvinelicornes_d, sugardaddy_d);
        }
        
        public CandiesSellerWPF.ServiceReference1.priceBusiness getPrice() {
            return base.Channel.getPrice();
        }
        
        public System.Threading.Tasks.Task<CandiesSellerWPF.ServiceReference1.priceBusiness> getPriceAsync() {
            return base.Channel.getPriceAsync();
        }
        
        public bool setPrice(int Skittles_cost_d, int cottoncandy_cost_d, int creamegg_cost_d, int jawbreaker_cost_d, int redvinelicornes_cost_d, int sugardaddy_cost_d) {
            return base.Channel.setPrice(Skittles_cost_d, cottoncandy_cost_d, creamegg_cost_d, jawbreaker_cost_d, redvinelicornes_cost_d, sugardaddy_cost_d);
        }
        
        public System.Threading.Tasks.Task<bool> setPriceAsync(int Skittles_cost_d, int cottoncandy_cost_d, int creamegg_cost_d, int jawbreaker_cost_d, int redvinelicornes_cost_d, int sugardaddy_cost_d) {
            return base.Channel.setPriceAsync(Skittles_cost_d, cottoncandy_cost_d, creamegg_cost_d, jawbreaker_cost_d, redvinelicornes_cost_d, sugardaddy_cost_d);
        }
        
        public bool setOrder(CandiesSellerWPF.ServiceReference1.userBusiness unUser, CandiesSellerWPF.ServiceReference1.Panier uneOrder) {
            return base.Channel.setOrder(unUser, uneOrder);
        }
        
        public System.Threading.Tasks.Task<bool> setOrderAsync(CandiesSellerWPF.ServiceReference1.userBusiness unUser, CandiesSellerWPF.ServiceReference1.Panier uneOrder) {
            return base.Channel.setOrderAsync(unUser, uneOrder);
        }
    }
}
